### ISSUE TITLE
GetFeatureOfInterestRequestDecoder no parse featureOfInterest parameter

### ISSUE THREAD

**Issue by ahuarte47** [52North/SOS#323]
Hi, the GetFeatureOfInterestRequestDecoder class decodes the GetFeatureOfInterest requests.

The source code reads the "featureOfInterest" parameter of the request using the "identifier" tag, but I think that it is a bug. It must use the "featureOfInterest" tag (JSONConstants.FEATURE_OF_INTEREST) as GetFeatureOfInterestResponseEncoder does. Also, the request samples use the "featureOfInterest" tag. I am wrong?

GetFeatureOfInterestRequestDecoder code:
https://github.com/52North/SOS/blob/e0eeee8cb5df425908b6d13df02fcec30d24d3d7/coding/json/src/main/java/org/n52/sos/decode/json/impl/GetFeatureOfInterestRequestDecoder.java#L100

GetFeatureOfInterestResponseEncoder code:
https://github.com/52North/SOS/blob/e0eeee8cb5df425908b6d13df02fcec30d24d3d7/coding/json/src/main/java/org/n52/sos/encode/json/impl/GetFeatureOfInterestResponseEncoder.java#L53

Best regards
Alvaro

**Comment by CarstenHollmann** [comment]
Yes, this is a bug. Thanks for reporting this issue.

**Comment by ahuarte47** [comment]
@CarstenHollmann thanks to you, and congratulations for this excelent software!

Best Regards
Alvaro

**Comment by ahuarte47** [comment]
Hi, the pull request https://github.com/52North/SOS/pull/324 fix it and works for me

**Comment by ahuarte47** [comment]
Thanks @CarstenHollmann !

**Comment by CarstenHollmann** [comment]
Hi @ahuarte47,
I had to undo the pull request because it was against the master branch.
The SOS master branch contains the current stable/latest release version.

Please create pull request to the [develop branch](https://github.com/52North/SOS/tree/develop).
Or if it is a hotfix, please create a pull request to the appropriate maintenance branch,[e.g. maintenance/4.3](https://github.com/52North/SOS/tree/maintenance/4.3).

**Comment by ahuarte47** [comment]
Done:
https://github.com/52North/SOS/pull/332

Thanks @CarstenHollmann !!!
