### ISSUE TITLE
Duplicate TimePeriod gml:id entered OK, but stops DescribeSensor retrieval of 'parent' PhysicalProcess

### ISSUE THREAD

**Issue by dbciar** [52North/SOS#352]
Hey,

I'm not sure if this is an issue or not - that no warning was given during InsertSensor calls that a duplicate ID is being used, but DescribeSensor then doesn't work due to this, I think it might be.  The following is with SOS 2.0, SML 2.0, POX binding, current development branch.

Using the InsertSensor example commands, inserting System Type -> System Instance -> Component Type -> Component Instance with one modification.

I copy/pasted the ValidTime element from the System Instance into the Component Instance thinking a system may have a different start time than some sensors connected to it, but I forgot to change the TimePeriod gml:id attribute, so they both had "validityPeriod" as the value.  The InsertSensor calls work with no problem, and DescribeSensor for the Component Instance (procedureID 'pressureDetector_of_ExampleHydrophone1') works correctly, but DescribeSensor for the System Instance (procedureID 'ExampleHydrophone1') gives the following error:

```
    <?xml version="1.0" encoding="UTF-8"?>
    <ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.1.0" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsAll.xsd">
      <ows:Exception exceptionCode="InvalidRequest" locator="Duplicate ID value 'validityPeriod'">
        <ows:ExceptionText>[XmlBeans validation error:] Duplicate ID value 'validityPeriod'</ows:ExceptionText>
      </ows:Exception>
    </ows:ExceptionReport>
``` 

I thought this might be something that shouldn't be allowed to be entered, similar to trying to enter a procedure or observation offering more than once as it causes DescribeSensor to fail.

**Comment by CarstenHollmann** [comment]
The gml:id is not an id which is globally unique, it should only be unique within the document where it occurs.

You have inserted different documents wherein the same gml:id occurs which is ok because in each document the gml:id is unique. 
 
The SOS stores the XML procedure description documents in the database and uses these documents in the response. In your case the SOS adds the Component to the System document but both have a ValidTime element with the same gml:id and during the validation check of the document the exception is thrown.

#356 fixes this issue by checking the gml:ids of the document for duplicity.
