### ISSUE TITLE
GetCapabilities violates Hydrology Profile Definition 5 (Identification with xlink:href)

### ISSUE THREAD

**Issue by DS-NV** [52North/SOS#520]
The current demo's [GetCapabilities-Answer](http://sensorweb.demo.52north.org/52n-sos-webapp/service?service=SOS&request=GetCapabilities) identifies procedures (and other things) not using xlink:href, as statet in Hydrology Profile Definition 5. The [GetDataAvailability-Answer](http://sensorweb.demo.52north.org/52n-sos-webapp/service?service=SOS&request=GetDataAvailability&version=2.0.0) conforms to Definition 5.

Is there a possibility to "Switch on" Hydrology Profile conformance in your software? Orc ould you change the Software and add the xlink:href Attribute?

Thank you
Daniel

**Comment by CarstenHollmann** [comment]
Hi Daniel,

the OGC OWS Common 1.1.0 (OGC 06-121r3) (defines the basic Capabilities), the OCC SOS 2.0 (OGC 12-006) and OG SWE Service Model (SWES) (OGC 09-001) (defining the Context element) do not use the gml:Reference, gml:AssociationAttributeGroup or xlink:simpleAttrs in the element definitions.

Therefore, it is not possible to use the xlink:href in the GetCapabilities answers for the identifiers because this attribute ist not defined for the elements by the standards mentioned above.

Best,
Carsten

**Comment by DS-NV** [comment]
Hi Carsten,

ok, thanks for the Explanation and sorry for already opening a ticket.

Have a nice day!
Daniel
