### ISSUE TITLE
NPR - Insert Sensor

### ISSUE THREAD

**Issue by dbciar** [52North/SOS#572]
Hi,

I'm trying to take the example XML from the OGC lightweight profile example and get it working with the SOS, and one of the submissions to see if the editing has got it into a usable format throws a NPR.

The InsertSensor request gist is [here](https://gist.github.com/dbciar/a66e92b76dd112a43eeea807b5e614e8).

I'm using version 4.4.1 of the SOS, downloaded from the URI below:
https://github.com/52North/sos/releases/download/v4.4.1/52n-sensorweb-sos-bundle-4.4.1.zip

**Comment by CarstenHollmann** [comment]
Hi @dbciar ,

the problem with your InsertSensor request is that you have defined an invalid SensorML namespace in the procedure description element. You have defined `xmlns="http://www.opengis.net/sensorML/2.0"` but correct is xmlns="http://www.opengis.net/sensorml/2.0"`. 

I have added a check for the namespace of the description and the procedureDescriptionFormat if they are equal. Instead of a NPE an OWS exception would be thrown and returned.
