### ISSUE TITLE
North52 as External Library

### ISSUE THREAD

**Issue by marcogrieco** [52North/SOS#627]
Hi,
i would like know if it is possible to use North52 as external library of an existing Java Project. I would like use it to expose sensor data (with the web services of North52) that are already in my database. How can i use North52 to do this? 

Thanks.

Marco

**Comment by CarstenHollmann** [comment]
Hi Marco,

the 52N SOS is implemented as a web service that uses several libraries which only provide a part of the full SOS functionality. It would be possible to use the 52N SOS libraries but you have to add all the required libraries to your project and you have to implement the start-up process of the SOS as it passes through the deployment/installation.

Or would it be possible to integrate the exiting Java Project into the SOS?

Which version of the SOS do you use?

If you need the observations in your existing Java Project the [Sensor Web REST-API](http://52north.github.io/series-rest-api/develop/index.html) might be an option to get these data from the SOS which is included in the current 52N SOS releases.

Best,
Carsten

**Comment by marcogrieco** [comment]
Hi,
i have to use the version 4.0.0 because my system is developed in Java6 and i have seen that the maximum version of the North52 that i can implement is the 4.0.0. Is it correct?

Is it a solution install the North52 and load data in it with the webservice?
North52 for me is the best solution but i would like know how to load all data from my system in North52 to expose them with standard North52 web services. 

Thanks in advance for the support.

Marco Grieco

**Comment by CarstenHollmann** [comment]
Hi Marco,

there is a version [4.0.1](https://github.com/52North/SOS/releases/tag/4.0.1) that has some fixes. Since version 4.1.x Java 7 is used to build the SOS, so 4.0.x should work with Java 6.

The 52N SOS uses the [Hibernate framework](http://hibernate.org/orm/) with for connecting and communicating with the database. The database model is defined in Hibernate mapping files which can be customized to existing database models. Depending on your database model it might be possible to customize the mapping files. Som infomation can be found here: https://wiki.52north.org/SensorWeb/SensorObservationServiceHibernateMapping

Another option is to insert migrate your exiting data into the 52N SOS database model via SQL scripts or ETL tools.

Best,
Carsten

**Comment by EHJ-52n** [comment]
Dear @marcogrieco,
in the case of an already existing database, you might consider our documentation about adjusting the hibernate mappings:

https://wiki.52north.org/SensorWeb/SensorObservationServiceHibernateMapping

In addition, this seems not to be an "issue" with the software but a question regarding the usage. Such questions should be discussed on our open mailing list: sensorweb@52north.org. Hence, I am closing this "issue". You are invited to [subscribe for free](https://list.52north.org/mailman/listinfo/sensorweb) and continue the discussion on the list.

Kind regards and please don't feel pushed back but invited to join the community!
