### ISSUE TITLE
Issue when using ObservableProperty that contains the word "depth"

### ISSUE THREAD

**Issue by EnocMartinez** [52North/SOS#643]
I've noticed an issue when injecting data to an SOS and the obserablePropety identifier contains the word "depth". Although InsertSensor and InsertResultTemplate are correctly processed by the application, when trying to inject some data an exception is returned ("The resultValues format does not comply to the resultStructure of the resultTemplate!"). 

However, using the same files but only changing the word depth for something else (e.g. "deepth") everything works perfectly. Attached there are files to illustrate both cases (the only difference is the word depth in KO files and deepth in OK files).

SOS info:
Version: 4.4.4
Branch: maintenance/4.4
Revision: 17831ec314cca51e08d909ae9ecec344597cf488
Build date: 2018-12-06 11:38:55+0100
Installation date: 2019-01-18 12:52:17

[depth_issue_files.zip](https://github.com/52North/SOS/files/2773005/depth_issue_files.zip)

**Comment by CarstenHollmann** [comment]
Hi @EnocMartinez,

thanks for reporting this.

For the support of inserting profile observations via the result handling operations the implementation checks the observedProperty identifier for `depth` and `height` for the case that the depht/height information are provided as an observedProperty.

Since you are inserting a complex observations the check for depth/height should not be done. I will check this an inform you.

Best,
Carsten

**Comment by CarstenHollmann** [comment]
Fixed in SOS release version 4.4.5 https://github.com/52North/SOS/releases/tag/v4.4.5.

**Comment by EnocMartinez** [comment]
Thanks a lot @CarstenHollmann  !
