### ISSUE TITLE
Delete Sensor - Data persistence

### ISSUE THREAD

**Issue by marcogrieco** [52North/SOS#647]
Hi,
there is a way to delete a sensor without lose all data about it? If i delete a sensor i can't see anymore all the observations related to it.

I need to perform a logical deletion, so the sensor will be not returned by the services but its  data persists (and i can query them).

Thanks in advance.

Marco

**Comment by CarstenHollmann** [comment]
Hi Marco,

the DeleteSensor operation is specified in the [OGC SOS standard](http://www.opengeospatial.org/standards/sos) and defines that the sesnor/procedure and all the related data should no longer be provided. This also applies to the observations produced by the deleted sensor/procedure.

In the 52N SOS implementation the sensor/procedure and the related observations are not deleted physically but they are marked as deleted so that they no longer provided and queryable.

It would be great if you could describe your use case in more detail?

As far as I understand it, you would like to disable the insertion of observations for a sensor/procedure but the data should be still queryable.

Thanks,
Carsten

**Comment by marcogrieco** [comment]
Hi Carsten,
i need to query data about deleted sensors and related observations after i delete the sensors.

I would like have a history about all sensors of my system, also the deleted sensors.

Is this possible o i have to query the database tables?

Thanks,

Marco

**Comment by CarstenHollmann** [comment]
Hi Marco,

this is not yet possible via the SOS because since we have not had this use case yet, such a funktionality was not implemented..

Therefore, you have to immediately query the dabase tables or if you need such a feature, you are welcome to become a contriubutor:

  https://52north.org/software/licensing/guidelines/

Best,
Carsten

**Comment by marcogrieco** [comment]
Ok.
Which tables i have to query to get all observations about a sensor? Which is the query that North52 executes to do the GetObservation WS?

Thanks.

**Comment by CarstenHollmann** [comment]
Hi Marco,

to get the observations for a procedure you have to create a query that joins the procedure, series and observaiton tables like this:

```
SELECT 
  observation.*
FROM 
  public.observation 
  INNER JOIN public.series ON series.seriesid = observation.seriesid
  INNER JOIN public.procedure ON procedure.procedureid = series.procedureid
WHERE 
  procedure.identifier = 'PROCEDURE_IDENTIFIER';
```

Best,
Carsten
